Following are the tasks assigned for day 1 and day 2

In [7]:
#printing a right pyramid
for i in range(6):
   for j in range (i):
    print('&',end='')
   print('')


&
&&
&&&
&&&&
&&&&&


In [15]:
#printing a left pyramid
n=6
for i in range(n,0,-1):
  j=i-1
  for k in range(j):
    print(' ',end='')
  for k in range(n-i):
    print('&',end='')
  print('')


     
    &
   &&
  &&&
 &&&&
&&&&&


In [21]:
#full pyramid
n=6
for i in range(n):
  j=2*i-1
  s1=int((2*n-j)/2)
  s2=s1
  for h in range(s1):
    print(' ',end='')
  for h in range(j):
    print('&',end='')
  for h in range(s2):
    print(' ',end='')
  print('')


            
     &     
    &&&    
   &&&&&   
  &&&&&&&  
 &&&&&&&&& 


In [22]:
#Numpy Basics

In [23]:
import numpy as np
arr=np.array([1,2,3,4,5])

In [24]:
#(a) Reversing the array
arr2=arr[::-1]
print(arr2)
#(b) Flattening
array1= np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
fl1=array1.flatten()
print(fl1)
fl1=array1.flatten('C') # Row major order
print(fl1)
#(C) comparing
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))
#(d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
j=np.bincount(x).argmax()
print('most freq element is ',np.bincount(x).argmax())
print('indices are : ')
for i in range(len(x)):
  if x[i] == j:
    print(i)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
j=np.bincount(y).argmax()
print('most freq element is ',np.bincount(y).argmax())
print('indices are : ')
for i in range(len(y)):
  if x[i] == j:
    print(i)
#(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print('sum of all elements is',np.sum(gfg))
print("Sum of gfg(row) : ", np.sum(gfg, axis = 0)) 
print("Sum of gfg(col) : ", np.sum(gfg, axis = 1))
#(f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print('sum of diag elements ',np.trace(n_array))
w, v = np.linalg.eig(n_array)
print('eigen value ',w)
print('eigen vector ',v)
print('Inverse',np.linalg.inv(n_array))
print('determinant',np.linalg.det(n_array))
#(g)
#1.
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]]
print('product of p and q')
print(np.dot(p,q))
print("\nCovariance matrices\n",
      np.cov(p,q))
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print('product of p and q')
print(np.dot(p,q))
print("covariance can't be found")
#(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nInner product")
print(np.inner(x, y))
print("\nouter product")
print(np.inner(x, y))
print("\nCartesian product is ")
print(np.cross(x,y))

[5 4 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
True
most freq element is  1
indices are : 
0
5
7
8
9
most freq element is  1
indices are : 
0
5
7
8
9
sum of all elements is 45
Sum of gfg(row) :  [[20  9 16]]
Sum of gfg(col) :  [[14]
 [16]
 [15]]
sum of diag elements  176
eigen value  [98.16835147 28.097044   49.73460452]
eigen vector  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant 137180.0000000001
product of p and q
[[16 19]
 [26 31]]

Covariance matrices
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
product of p and q
[[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance can't be found

Inner product
[[17 52]
 [13 62]]

outer product
[[17 52]
 [13 62]]

Cartesian product is 
[[-20   4   7]
 [-84  36  20]]


In [25]:
#(a)
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
#(i)
print(np.absolute(array))
#(ii)
arr=array.flatten()
x = np.percentile(arr, 25)
print('25th percentile',x)
x = np.percentile(arr, 50)
print('50th percentile',x)
x = np.percentile(arr, 75)
print('75th percentile',x)
#(iii)
F_r=array.flatten('C')
#print(F_r)
print('For Row major')
print('mean is',np.mean(F_r))
print('median is',np.median(F_r))
print('standard deviation is ',np.std(F_r))
F_r=array.flatten('F')
#print(F_r)
print('For col major')
print('mean is',np.mean(F_r))
print('median is',np.median(F_r))
print('standard deviation is ',np.std(F_r))
#(b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print ("Floor values : \n",np.floor(a))
print ("ceil values : \n",np.ceil(a))
print ("truncated values : \n",np.trunc(a))
print ("rounded values : \n",np.round(a))

[[1 2 3]
 [4 5 6]]
25th percentile -3.5
50th percentile -0.5
75th percentile 2.5
For Row major
mean is -0.5
median is -0.5
standard deviation is  3.8622100754188224
For col major
mean is -0.5
median is -0.5
standard deviation is  3.8622100754188224
Floor values : 
 [-2. -2. -1.  0.  1.  1.  3.]
ceil values : 
 [-1. -1. -0.  1.  2.  2.  3.]
truncated values : 
 [-1. -1. -0.  0.  1.  1.  3.]
rounded values : 
 [-2. -2. -0.  0.  2.  2.  3.]


In [26]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
#(i)
print('sorted array',np.sort(array))
#(ii)
out_arr = np.argsort(array)
print('indices of sorted array',out_arr)
#(iii)
print('4',"smallest elements of the array")
t=np.sort(array)
k=t[:4]
print(k)
print('5 largest elements are ')
print((t[::-1])[:5])
#(b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
#(i)
print('Integer elements are')
for i in range(len(array)):
  if np.floor(array[i]) == array[i]:
    print(array[i])
print('Float elements are')
for i in range(len(array)):
  if np.floor(array[i]) != array[i]:
    print(array[i])

sorted array [ 10  16  16  52  54  62 453]
indices of sorted array [0 3 4 1 5 2 6]
4 smallest elements of the array
[10 16 16 52]
5 largest elements are 
[453  62  54  52  16]
Integer elements are
1.0
2.0
3.0
2.0
Float elements are
1.2
2.2
